### ISSUE TITLE
Remove "Resolve NAME.html for /name/"

### ISSUE THREAD

**Issue by lidel** [ipfs-shipyard/ipfs-protocol-compliance-suite#2]
README states: 

* Resolve NAME.html for /name/

I don't think this is something we do  in go-ipfs:
https://bafybeibz4qxl7t2cfkizkkiyqbxbmfixh4hnv6dd37xkritdrivqcdniti.ipfs.dweb.link/name/

only thing that we do is `/name/` resolving to `/name/index.html` (if present)

**Comment by RangerMauve** [comment]
Sounds good. I updated js-ipfs-fetch to remove this functionality, and I'll update the README after merging your fleek PR. 😁

**Comment by RangerMauve** [comment]
Resolved in the latest commit.
